#!/bin/bash

repo="${REPO_URL:-barolab}"
errs="$(pwd)/errors"

push() {
	f=$1
    image=${f%Dockerfile}
	base=${image%%\/*}
	dir=$(dirname "$f")
	suite=${dir##*\/}

    if [[ -z "$suite" ]] || [[ "$suite" == "$base" ]]; then
		suite=latest
	fi

	n=0
	until [ $n -ge 5 ]; do
		docker push "${repo}/${base}:${suite}" && break
		info "Try #$n failed... sleeping for 15 seconds"
		n=$((n + 1))
		sleep 15
	done

	# also push the tag latest for "stable" (chrome), "tools" (wireguard) or "3.5" tags for zookeeper
	if [[ "$suite" == "stable" ]] || [[ "$suite" == "3.5" ]] || [[ "$suite" == "tools" ]]; then
		info "Tagging ${repo}/${base}:${suite} to ${repo}/${base}:latest"
		docker tag "${repo}/${base}:${suite}" "${repo}/${base}:latest"
		docker push "${repo}/${base}:latest"
	fi
}

if [ "$1" == "" ]; then
    for project in **/Dockerfile; do
        push "${project}"
    done
else
    push "$1"
fi

if [[ ! -f "$errs" ]]; then
	echo "No errors, hooray !"
else
	echo "[ERROR] Some images did not build correctly, see below." >&2
	echo "These images failes : $(cat "$errs")" >&2
	exit 1
fi
